# Generated by Django 3.2.15 on 2022-09-29 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0008_product_is_featured'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='is_featured',
        ),
        migrations.AddField(
            model_name='cake_list',
            name='is_featured',
            field=models.BooleanField(default=False),
        ),
    ]
